# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('link', models.CharField(max_length=2000)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['time'],
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
