# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20170909_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='realLink',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
